# Basic operations :

## -Element wise operation

# Arthimetic operation 

In [1]:
import numpy as np

In [2]:
a = np.arange(5)

In [3]:
a

array([0, 1, 2, 3, 4])

In [4]:
b = np.ones(5,dtype='int8')

In [5]:
b

array([1, 1, 1, 1, 1], dtype=int8)

In [6]:
# adding a and b

a+b

array([1, 2, 3, 4, 5])

In [7]:
# subtraction

a-b

array([-1,  0,  1,  2,  3])

In [8]:
a*b

array([0, 1, 2, 3, 4])

In [9]:
a/b

array([0., 1., 2., 3., 4.])

In [10]:
b/a

C:\Users\varsh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [11]:
a*a*b

array([ 0,  1,  4,  9, 16])

In [12]:
a--a # here - after - results in plus.

array([0, 2, 4, 6, 8])

In [13]:
b--b

array([2, 2, 2, 2, 2], dtype=int8)

In [14]:
a-+b # here - after + results minus.

array([-1,  0,  1,  2,  3])

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [18]:
arr.dot(arr)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Comparision operator

In [19]:
a = np.array([1,2,3,4])
b = np.array([6,1,2,4])
print(a,b)

[1 2 3 4] [6 1 2 4]


In [20]:
a==b

array([False, False, False,  True])

In [21]:
a!=b

array([ True,  True,  True, False])

In [22]:
a>b

array([False,  True,  True, False])

In [23]:
a<b

array([ True, False, False, False])

In [24]:
c = np.array([1,2,3,4])

In [25]:
print(a,"\n",b,'\n',c)

[1 2 3 4] 
 [6 1 2 4] 
 [1 2 3 4]


## array_equal( )

In [26]:
np.array_equal(a,b)

False

In [27]:
np.array_equal(a,c)

True

In [28]:
c = np.arange(1,6)
c

array([1, 2, 3, 4, 5])

In [29]:
np.array_equal(a,c) # because the legnth is not same

False

# Logical operation :

In [30]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)
c = np.array([0,1,1,0],dtype=bool)

In [31]:
a

array([ True,  True, False, False])

In [32]:
b

array([ True, False,  True, False])

In [33]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [34]:
np.logical_not(a)

array([False, False,  True,  True])

In [35]:
np.logical_and(a,b)

array([ True, False, False, False])

In [36]:
np.logical_not(np.logical_or(a,b))

array([False, False, False,  True])

In [37]:
np.logical_and(np.logical_not(a),np.logical_or(b,c))

array([False, False,  True, False])

In [38]:
np.logical_xor(a,b)

array([False,  True,  True, False])

In [39]:
a&b  #and

array([ True, False, False, False])

In [40]:
a|b #or

array([ True,  True,  True, False])

In [41]:
a^b #xor

array([False,  True,  True, False])

In [42]:
~a #not

array([False, False,  True,  True])

In [43]:
a<<1

array([2, 2, 0, 0], dtype=int32)

In [44]:
a>>1

array([0, 0, 0, 0], dtype=int32)

In [45]:
a>>b

array([0, 1, 0, 0], dtype=int8)

In [46]:
arr  = np.eye(3,dtype = 'int8')

In [47]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [48]:
arr1 = np.zeros((3,3),dtype = 'int8')
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [49]:
np.logical_or(arr,arr1)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

# Transcidental Functions:

In [50]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [51]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [52]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [53]:
np.log(arr)

C:\Users\varsh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [54]:
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [55]:
np.cos(np.log(arr))

C:\Users\varsh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
C:\Users\varsh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in cos
  """Entry point for launching an IPython kernel.


array([        nan,  1.        ,  0.7692389 ,  0.45483242,  0.18345697,
       -0.03863197])

# Shape Mismatch :

In [56]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [57]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [58]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
b = np.array([1,2,3,4])

In [ ]:
a+b

# Basic Reductions :

## Computing sums

In [ ]:
arr = np.arange(5)

In [ ]:
arr

In [ ]:
np.sum(arr)

In [ ]:
np.sum(arr[0:4])

In [ ]:
arr1 = np.arange(10)

In [ ]:
arr1

In [ ]:
np.sum(arr1)

In [ ]:
np.sum(arr) + np.sum(arr1)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
np.sum(arr)

In [ ]:
np.sum(arr,axis=0) # axis = 0 indicates it will add column wise

In [ ]:
np.sum(arr,axis=1)  # axis = 1 indicates it will add row wise

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
arr

In [ ]:
np.sum(arr)

In [ ]:
np.sum(arr,axis=0)

In [ ]:
np.sum(arr[0::],axis=1)

In [ ]:
np.sum(arr[-1::],axis=1)

# MIN-MAX :

In [ ]:
arr = np.array([100,44,78,98,47,23,90])
print(arr)

In [ ]:
np.min(arr)

In [ ]:
np.argmin(arr)

In [ ]:
np.max(arr)

In [ ]:
np.argmax(arr)

In [ ]:
np.min(arr[0:5])

In [ ]:
np.max(arr[-1:-5:-1])

# Logical Operations :

In [ ]:
np.all([True,False,True,False])

In [ ]:
np.all([True,True,True])

In [ ]:
np.any([True,False,True,False])

In [ ]:
np.any([False,False,False,False])

In [ ]:
arr = np.ones((4,4),dtype='int8')
print(arr)

In [ ]:
np.all(arr)

In [ ]:
arr = np.zeros((4,4),dtype='int8')
print(arr)

In [ ]:
np.all(arr)

In [ ]:
np.all(arr==0)

In [ ]:
np.all(arr!=0)

In [ ]:
arr1 = np.eye(4,dtype='int8')

In [ ]:
print(arr1)

In [ ]:
np.any(arr1)

In [ ]:
np.all(arr1)

In [ ]:
np.any(arr==1)

In [ ]:
np.any(arr1!=0)

In [ ]:
np.any([np.all(arr1),np.any(arr1!=0)])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,3,7,5])  

In [ ]:
np.any(a==b)

In [ ]:
np.all(a!=b)

In [ ]:
np.any(a<=b)

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([6, 1, 2, 4])
c = np.array([1, 2, 3, 4])

In [ ]:
((a<b)&(c>b)).any()

true false false false
false true true false

------------------------
and function :
------------------------
false false false false
-------------------------
any function :
------------------------
false ***


In [ ]:
c>b

In [ ]:
a<b

In [ ]:
(a<b)&(c>b)


# statistics

## Mean :

In [61]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
np.mean(arr)

4.5

In [63]:
np.mean(arr[1:8])

4.0

In [64]:
arr1 = np.array([[1,2,3],[5,6,1]])
print(arr1)

[[1 2 3]
 [5 6 1]]


In [65]:
np.mean(arr1)

3.0

In [66]:
np.mean(arr1,axis=0)

array([3., 4., 2.])

In [68]:
np.mean(arr1,axis=1)

array([2., 4.])

In [69]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [70]:
np.mean(arr2)

6.5

In [71]:
np.mean(arr2,axis=1)

array([[ 2.5,  3.5,  4.5],
       [ 8.5,  9.5, 10.5]])

In [72]:
np.mean(arr2,axis=0)

array([[4., 5., 6.],
       [7., 8., 9.]])

## Median :

In [73]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
np.median(a)

4.5

In [75]:
b = np.arange(11)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [76]:
np.median(b)

5.0

In [77]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [78]:
np.median(arr)

3.5

In [79]:
np.median(arr,axis=0)

array([2.5, 3.5, 4.5])

In [81]:
np.median(arr,axis=1)

array([2., 5.])

In [86]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [87]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.median(arr,axis =0)

array([3., 4., 5., 6.])

In [89]:
np.median(arr)

4.5

In [92]:
np.median(([[[1,2,3],[4,5,6]],[[3,4,5],[6,7,1]]]),axis = 0)


array([[2. , 3. , 4. ],
       [5. , 6. , 3.5]])

In [93]:
np.median(([[[1,2,3],[4,5,6]],[[3,4,5],[6,7,1]]]),axis = 1)


array([[2.5, 3.5, 4.5],
       [4.5, 5.5, 3. ]])

## Standard Deviation :

In [94]:
arr = np.array([[1,2,3],[4,5,6]])

In [95]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr.std()

1.707825127659933

In [97]:
np.std(arr)

1.707825127659933

In [98]:
np.std(arr,axis=0)

array([1.5, 1.5, 1.5])

In [99]:
arr.std(axis=0)

array([1.5, 1.5, 1.5])

In [100]:
np.std(arr,axis=1)

array([0.81649658, 0.81649658])

In [101]:
arr.std(axis=1)

array([0.81649658, 0.81649658])