# Copies and Views :

In [5]:
import numpy as np

In [7]:
arr = np.arange(0,200,15)
arr

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180,
       195])

## - Shallow Copy

In [8]:
new = arr[3:10]

In [9]:
new

array([ 45,  60,  75,  90, 105, 120, 135])

# shares_memory( )

In [13]:
np.shares_memory(arr,new)

True

### Here True value indicates that the arr and new both arrays shares the same memory that means if any changes made to new named array that will also effects the arr - array

In [14]:
new[4]=100

In [15]:
new

array([ 45,  60,  75,  90, 100, 120, 135])

In [16]:
arr

array([  0,  15,  30,  45,  60,  75,  90, 100, 120, 135, 150, 165, 180,
       195])

## - Deep Copy

In [18]:
arr = np.arange(0,20,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18])

In [23]:
new = arr[2:7].copy()
new

array([ 6,  9, 12, 15, 18])

In [21]:
np.shares_memory(arr,new)

False

### Here False value indicates that the arr and new both arrays doesn't shares the same memory that means if any changes made to new named array that won't also effects the arr - array

In [24]:
new[3] = 1000

In [25]:
new

array([   6,    9,   12, 1000,   18])

In [26]:
arr

array([ 0,  3,  6,  9, 12, 15, 18])