# Advanced Indexing :

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
mask = (arr%2==0) # giving the condition 

In [5]:
print(mask)  # it will return in boolean format

[False  True False  True False  True False  True False  True]


In [6]:
arr[mask] # displays only an array of elements which are true

array([ 2,  4,  6,  8, 10])

#### Indexing with a mask can be very useful to assign a new values to sub-arrays

In [7]:
arr[mask] = 100

In [8]:
arr # it will assign 100 value to the all true indexed values.

array([  1, 100,   3, 100,   5, 100,   7, 100,   9, 100])

###  Indexing an array with that array of integers.

In [10]:
arr = np.arange(0,100,10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
arr[[2,3,5,8,1]]

array([20, 30, 50, 80, 10])

### New values can be assigned 

In [12]:
arr[[6,9]] = 100
arr

array([  0,  10,  20,  30,  40,  50, 100,  70,  80, 100])