# Importing the Numpy Library

In [1]:
import numpy as np

### Showing the how numpy library works.

In [2]:
# Normal list 

list1 = range(1000)
%timeit [i**2 for i in list1]

652 µs ± 13.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
list2 = np.arange(1000)
%timeit list2**2 

2.78 µs ± 23.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Creating the arrays using numpy

## 1-D Array

In [38]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [7]:
arr # display the array

array([1, 2, 3, 4])

In [10]:
type(arr) #display the type

numpy.ndarray

In [13]:
arr.shape #gives the shape of the array

(4,)

In [14]:
arr.ndim #Gives the dimensions of the array

1

In [15]:
len(arr)

4

## 2-D Array

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
type(arr)

numpy.ndarray

In [18]:
arr.ndim

2

In [19]:
arr.shape

(2, 3)

In [20]:
len(arr)

2

In [21]:
print(arr.shape) #2 rows and 3 columns

(2, 3)


## 3-D Array

In [22]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
arr.shape 

(2, 2, 2)

#### the above (2,2,2) gives 2 axis , 2 rows and 2 columns.

In [24]:
arr.ndim

3

In [25]:
type(arr)

numpy.ndarray

In [26]:
len(arr)

2

# Functions for Creating Arrays

## arange( )

In [27]:
arr = np.arange(10)

##### arange(10) will retuen the evenly spaced vales within a given interval - 10

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
arr = np.arange(1,10,2)
print(arr)  #2 is step

[1 3 5 7 9]


## linspace( )

In [48]:
arr = np.linspace(1,10)

##### linspace(1,10) will return the evenly spaced numbers over a specufied interval
##### By default it will display 50 numbers with in the given range

In [49]:
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [50]:
len(arr)

50

In [51]:
type(arr)

numpy.ndarray

In [52]:
arr.shape

(50,)

#### From in the above output each number has the eqaul differences...

In [53]:
# we can also specify the how many numbers to display with in the given range

arr1 = np.linspace(1,10,5) #so,it will give 5 evenly spaced numbers with in the range 1,10
print(arr1)

[ 1.    3.25  5.5   7.75 10.  ]


## ones( )

In [65]:
arr = np.ones((2,2))

##### ones(2,2) will display a new array of given shape and type which was filled with only ones.

In [66]:
print(arr)

[[1. 1.]
 [1. 1.]]


In [67]:
arr.dtype

dtype('float64')

In [68]:
arr1=np.ones((2,2),dtype="int8")

In [69]:
print(arr1)

[[1 1]
 [1 1]]


In [70]:
arr1.dtype

dtype('int8')

In [71]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


## Zeros

In [76]:
arr = np.zeros((3,2))

#### zeros(3,2) will display a new array of given shape and type which was filled with only zeros.

In [78]:
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [79]:
arr.dtype

dtype('float64')

In [80]:
arr = np.zeros((4,4),dtype='int8')
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [81]:
arr.dtype

dtype('int8')

## diag

#### it constructs a diagonal array or to extract the diagonal from the array

In [83]:
arr = np.diag([1,2,3,4])

#### construct a diagonal array

In [86]:
print(arr) # [1,2,3,4] i have specified 4 elements it will create 4x4 matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### Extract the diagonal

In [85]:
np.diag(arr)

array([1, 2, 3, 4])

## eye( ) - creates Identity Matrix

In [101]:
arr = np.eye(3,dtype='int8') # will create 3x3 matrix

In [102]:
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Random = random values,random samples from a uniform distribution in a given shape

### - random.rand( )

### - random.randn( )

In [95]:
arr = np.random.rand(5) # will display any 5 random numbers

In [96]:
print(arr)

[0.07124441 0.08039353 0.06315472 0.58759715 0.58700314]


In [103]:
arr1 = np.random.rand(3,2)
print(arr1)

[[0.15715521 0.52290491]
 [0.2388206  0.72909853]
 [0.66347219 0.33201249]]


In [97]:
arr = np.random.randn(5) # will display from the standard normal distribution

In [98]:
print(arr)

[-0.38811826 -0.90626959 -0.20764222  1.28346315  1.41440218]


In [100]:
arr = np.random.randn(2,3)
print(arr)

[[-0.69191808  0.34710464 -0.20037087]
 [-0.20475482 -1.58416123  1.10615419]]


# Summary

## - Functions ( )
### -arange( )
### -linspace( )
### -ones( )
### -zeros( )
### -eye( )
### -diag( )
### -random.rand( )
### -random.randn( )