### Numpy has the advantage that it supports the datatypes of python.

In [1]:
import numpy as np

In [6]:
arr = np.arange(10)
arr.dtype

dtype('int32')

In [7]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### I can instialise the datatype

In [8]:
arr = np.arange(10,dtype='float64')

In [9]:
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [10]:
arr = np.zeros((4,4))

# by default it takes floating vales

In [11]:
print(arr)
print(arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [15]:
arr = np.zeros((4,4),dtype="int8",order = 'c')
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int8


In [16]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
arr = np.ones(10,dtype='int8')
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [20]:
arr = np.eye(4,dtype="int8")
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

## Complex Data Type

In [22]:
arr = np.array([1+2j,2+3j])
print(arr)
print(arr.dtype)

[1.+2.j 2.+3.j]
complex128


In [24]:
arr = np.array([[[1+2j],[2+3j]],[[4+5j],[7+8j]]])

In [25]:
print(arr)
print(arr.dtype)

[[[1.+2.j]
  [2.+3.j]]

 [[4.+5.j]
  [7.+8.j]]]
complex128


## Boolean data type

In [26]:
arr = np.array([False,True,False,True,True])
print(arr)
print(arr.dtype)

[False  True False  True  True]
bool


In [27]:
arr = np.array([[False],[True],[True]])
print(arr)

[[False]
 [ True]
 [ True]]


In [29]:
arr = np.array([[False,True,True],[False,True,True],[False,True,True]])
print(arr)

[[False  True  True]
 [False  True  True]
 [False  True  True]]


In [30]:
arr = np.array(['varshini','Beeneedi','Hello'])
print(arr.dtype)

<U8


In [32]:
len_checker = np.vectorize(len)
arr_len = len_checker(arr)
print(arr_len)
print(arr_len.max())

[8 8 5]
8
