# Slicing , Indexing and Iterating

## For One-Dimensional Array

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#getting value by index

arr[3]

3

In [4]:
arr[0:9] #getting values by slicing

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [8]:
arr[:10:2]

array([0, 2, 4, 6, 8])

In [9]:
arr[::3]

array([0, 3, 6, 9])

In [13]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
arr[:-10:-2]

array([9, 7, 5, 3, 1])

In [22]:
arr[-2:-8:-2]

array([8, 6, 4])

In [23]:
for i in arr: #iterating
    print(i)

0
1
2
3
4
5
6
7
8
9


# Multi-Dimensional Array 
### - arrays can have one index per axis. These indices are given in a tuple separated by commas
# Iteration
### - iterations in the mutlidimensional arrays can be done with respect to the first axis

In [30]:
#creating an array using for loop
def num(x,y):
    return 10*x+y

In [31]:
arr = np.fromfunction(num,(5,5),dtype="int")
print(arr)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


# Indexing

In [32]:
arr[2]

array([20, 21, 22, 23, 24])

In [33]:
arr[-1]

array([40, 41, 42, 43, 44])

In [35]:
arr[2,3]

23

In [36]:
arr[1,2]

12

In [37]:
#slicing a particular column from the array

arr[3,4]

34

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [40]:
#slicing some values from a particular column

arr[0:3,2]

array([ 2, 12, 22])

In [47]:
arr[:3,3]

array([ 3, 13, 23])

In [48]:
arr[:,4]

array([ 4, 14, 24, 34, 44])

In [52]:
arr[:-4:-1,-1]

array([44, 34, 24])

In [60]:
arr[2,1:4]

array([21, 22, 23])

In [59]:
arr[3,:]

array([30, 31, 32, 33, 34])

In [58]:
arr[2,-1:-4:-2]

array([24, 22])

# 3-D array

In [67]:
arr = np.array([[[0,1,2],[10,11,12]],[[100,101,102],[110,112,113]]])
print(arr)

[[[  0   1   2]
  [ 10  11  12]]

 [[100 101 102]
  [110 112 113]]]


In [68]:
arr.shape  
 
# 2 is axis
# 2 is rows
# 3 is columns

(2, 2, 3)

In [69]:
# indexing
arr[0,0,1]

1

In [70]:
#assigning

arr[1,1,2]=500

In [71]:
arr

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 112, 500]]])

In [72]:
#slicing 

arr[:,:,:]

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 112, 500]]])

In [73]:
arr[1:,:]

array([[[100, 101, 102],
        [110, 112, 500]]])

In [74]:
arr[0,0,0:2]

array([0, 1])

In [79]:
arr[0:2,0:1,:2]

array([[[  0,   1]],

       [[100, 101]]])

In [80]:
# iteration

for i in arr:
    print(i)

[[ 0  1  2]
 [10 11 12]]
[[100 101 102]
 [110 112 500]]


In [81]:
for i in arr.flat:
    print(i)

0
1
2
10
11
12
100
101
102
110
112
500
